apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25.3
      command: ["/bin/sh"]
      args:
        - "-c"
        - "echo hello"
      resources: {}
  restartPolicy: Never